TOTO

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -122,10 +122,14 @@ jobs:
       - checkout
       - run:
           name: Heroku Deploy
-          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/guarded-chamber-15621.git master
+          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
       - run:
           name: Smoke Test
-          command: echo todo 
+          command: HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
+if [ "$HTTPCODE" -ne 200 ];then
+    echo "heroku app not responding, failing deploy"
+    exit 1
+fi
 
 workflows:
   version: 2
